In [1]:
from datetime import datetime
import pandas as pd
import requests

In [2]:
feather_path_gdvDespesasExcel = '/mnt/c/airflow/dags/karhub-project/resources/feather/gdvDespesasExcel.feather'
feather_path_gdvReceitasExcel = '/mnt/c/airflow/dags/karhub-project/resources/feather/gdvReceitasExcel.feather'

In [3]:
df_despesas = pd.read_feather(feather_path_gdvDespesasExcel)
df_receita = pd.read_feather(feather_path_gdvReceitasExcel)

In [43]:
df_despesas

,Fonte de Recursos,Despesa,Liquidado,Unnamed: 3
0,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,31900119 - ATRASADOS-OUTROS PODERES/MINIST.PUB...,"79.760.504,67",NaN
1,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,31900124 - COMPLEMENTACAO DE APOSENTADORIA,"1.850.834.374,26",NaN
2,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,31900125 - COMPLEMENTACAO DE APOSENTADORIA - 1...,"124.536.202,87",NaN
3,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,31900325 - COMPLEMENTACAO DE PENSAO,"10.948.297,00",NaN
4,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,31900326 - COMPLEMENTACAO DE PENSAO - 13º SALARIO,"521.632,30",NaN
...,...,...,...,...
2030,087 - OP.CRED.CONTR.EXTERIOR-DOT.INIC.CR.SUP-I...,44905112 - INSTALACOES,"2.545.097,24",NaN
2031,087 - OP.CRED.CONTR.EXTERIOR-DOT.INIC.CR.SUP-I...,44905130 - EXECUCAO DE OBRAS E INSTALACOES,"32.829.959,39",NaN
2032,087 - OP.CRED.CONTR.EXTERIOR-DOT.INIC.CR.SUP-I...,44905210 - VEICULOS DIVERSOS,"755.209,26",NaN
2033,087 - OP.CRED.CONTR.EXTERIOR-DOT.INIC.CR.SUP-I...,44905234 - OUTROS EQUIPAMENTOS E MATERIAL PERM...,"2.098.500,00",NaN
2034,None,TOTAL,"257.997.692.438,95",NaN

In [6]:
url = "https://economia.awesomeapi.com.br/json/daily/USD-BRL?start_date=20220622&end_date=20220622"

response = requests.get(url)

if response.status_code == 200:
    data = response.json()
    if len(data) > 0:
        high_rate = float(data[0]['high'])
        print(f"Taxa de compra (high): {high_rate}")

Taxa de compra (high): 5.1954

In [5]:
data

[{'code': 'USD',
  'codein': 'BRL',
  'name': 'Dólar Americano/Real Brasileiro',
  'high': '5.1954',
  'low': '5.1944',
  'varBid': '0.001',
  'pctChange': '0.02',
  'bid': '5.1945',
  'ask': '5.1955',
  'timestamp': '1655942340',
  'create_date': '2022-06-22 20:59:00'}]

In [44]:
df_receita

,Fonte de Recursos,Receita,Arrecadado
0,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11130111 - IRRF - IMP.RENDA PESSOA FISICA-PRIN...,"4267858335,83"
1,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11130311 - IRRF-IMP. RENDA RET. FTE-TRABALHO-P...,"4323772997,93"
2,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11130341 - IRRF-OUTROS RENDIMENTOS-PRINCIPAL,"123071158,14"
3,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11180121 - IPVA - IMP. PROPR. VEIC. AUTOM - P...,"8202995933,47"
4,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11180122 - IPVA - MULTAS E JUROS,"6927,39"
...,...,...,...
280,085 - RECURSOS VINCULADOS FEDERAIS-INTRA,89900011 - DEMAIS RECEITAS DE CAPITAL-PRINCIPA...,"12392104,67"
281,086 - OUTRAS FONTES DE RECURSOS-INTRA,89100011 - INTEGRALIZACAO CAPITAL SOCIAL-PRINC...,"137377128,78"
282,087 - OP.CRED.CONTR.EXTERIOR-DOT.INIC.CR.SUP-I...,89100011 - INTEGRALIZACAO CAPITAL SOCIAL-PRINC...,"46441531,83"
283,099 - EXTRA ORCAMENTARIA,13210011 - REMUNERACAO DEPOSITOS BANCARIOS - ...,0
284,None,TOTAL,"257443703586,69"

In [28]:
df_despesas
df_despesas['Count'] = df_despesas.groupby('Despesa')['Despesa'].transform('count')

In [37]:
df_receita['Count'] = df_receita.groupby('Receita')['Receita'].transform('count')

In [38]:
df_receita

,Fonte de Recursos,Receita,Arrecadado,Count
0,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11130111 - IRRF - IMP.RENDA PESSOA FISICA-PRIN...,"4267858335,83",8
1,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11130311 - IRRF-IMP. RENDA RET. FTE-TRABALHO-P...,"4323772997,93",3
2,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11130341 - IRRF-OUTROS RENDIMENTOS-PRINCIPAL,"123071158,14",6
3,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11180121 - IPVA - IMP. PROPR. VEIC. AUTOM - P...,"8202995933,47",2
4,001 - TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11180122 - IPVA - MULTAS E JUROS,"6927,39",2
...,...,...,...,...
280,085 - RECURSOS VINCULADOS FEDERAIS-INTRA,89900011 - DEMAIS RECEITAS DE CAPITAL-PRINCIPA...,"12392104,67",3
281,086 - OUTRAS FONTES DE RECURSOS-INTRA,89100011 - INTEGRALIZACAO CAPITAL SOCIAL-PRINC...,"137377128,78",6
282,087 - OP.CRED.CONTR.EXTERIOR-DOT.INIC.CR.SUP-I...,89100011 - INTEGRALIZACAO CAPITAL SOCIAL-PRINC...,"46441531,83",6
283,099 - EXTRA ORCAMENTARIA,13210011 - REMUNERACAO DEPOSITOS BANCARIOS - ...,0,16
284,None,TOTAL,"257443703586,69",1

TRATATIVAS - RECEITA

In [ ]:
df_receita[['ID Fonte Recurso', 'Nome Fonte Recurso']] = df_receita['Fonte de Recursos'].str.extract(r'^(\d+) - (.*)$')
pd.options.display.float_format = '{:.2f}'.format
df_receita['Arrecadado'] = df_receita['Arrecadado'].str.replace('.', '').str.replace(',', '.').astype(float)
df_receita = df_receita[['ID Fonte Recurso', 'Nome Fonte Recurso', 'count', 'Arrecadado']]
grouped_df_receita = df_receita.groupby(['ID Fonte Recurso', 'Nome Fonte Recurso', 'count']).agg(
    {'Arrecadado': 'sum'}).reset_index()

In [39]:
grouped_df_receita.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284 entries, 0 to 283
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID Fonte Recurso    284 non-null    object
 1   Nome Fonte Recurso  284 non-null    object
 2   Receita             284 non-null    object
 3   Arrecadado          284 non-null    float64
dtypes: float64(1), object(3)
memory usage: 9.0+ KB

TRATATIVAS - DESPESAS

In [19]:
df_despesas[['ID Fonte Recurso', 'Nome Fonte Recurso']] = df_despesas['Fonte de Recursos'].str.extract(r'^(\d+) - (.*)$')
pd.options.display.float_format = '{:.2f}'.format
df_despesas['Liquidado'] = df_despesas['Liquidado'].str.replace('.', '').str.replace(',', '.').astype(float)
df_despesas = df_despesas[['ID Fonte Recurso', 'Nome Fonte Recurso', 'Despesa', 'Liquidado']]
grouped_df_despesas = df_despesas.groupby(['ID Fonte Recurso', 'Nome Fonte Recurso', 'Despesa']).agg(
    {'Liquidado': 'sum'}).reset_index()

In [40]:
grouped_df_despesas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2034 entries, 0 to 2033
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID Fonte Recurso    2034 non-null   object
 1   Nome Fonte Recurso  2034 non-null   object
 2   Despesa             2034 non-null   object
 3   Liquidado           2034 non-null   float64
dtypes: float64(1), object(3)
memory usage: 63.7+ KB

In [21]:
total_after = grouped_df_despesas['Liquidado'].sum()

In [22]:
total_after

np.float64(257997692438.95)

Join - das duas tabelas

In [43]:
from google.cloud import bigquery
from google.oauth2 import service_account

def process_data(df, bid_rate, tipo):
    df[['ID Fonte Recurso', 'Nome Fonte Recurso']] = df['Fonte de Recursos'].str.extract(r'^(\d+) - (.*)$')

    df[tipo] = df[tipo].str.replace('.', '').str.replace(',', '.').astype(float)

    grouped_df = df.groupby(['ID Fonte Recurso', 'Nome Fonte Recurso']).agg({
        tipo: 'sum'
    }).reset_index()

    grouped_df[tipo] = grouped_df[tipo] * bid_rate

    return grouped_df

def data_join(grouped_df_receita, grouped_df_despesas):

    df = pd.merge(grouped_df_receita, grouped_df_despesas, on=['ID Fonte Recurso', 'Nome Fonte Recurso'], how='outer')
    df['Arrecadado'].fillna(0.00, inplace=True)
    df['Liquidado'].fillna(0.00, inplace=True)
    df['dt_insert'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    df['dt_insert'] = pd.to_datetime(df['dt_insert'])

    return df

url = "https://economia.awesomeapi.com.br/json/daily/USD-BRL?start_date=20220622&end_date=20220622"

def request_api_dolar(url):
    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        if len(data) > 0:
            return float(data[0]['bid'])

In [44]:
bid_rate = request_api_dolar(url)

grouped_df_receita = process_data(df_receita, bid_rate, 'Arrecadado')
grouped_df_despesas = process_data(df_despesas, bid_rate, 'Liquidado')

df_merged = data_join(grouped_df_receita, grouped_df_despesas)

/tmp/ipykernel_13315/2676304745.py:17: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Arrecadado'].fillna(0.00, inplace=True)
/tmp/ipykernel_13315/2676304745.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Liquidado'].fillna(0.00, inplace=True)

In [26]:
df_merged = pd.merge(grouped_df_receita, grouped_df_despesas, on=['ID Fonte Recurso', 'Nome Fonte Recurso'], how='outer')
df_merged['Arrecadado'].fillna(0.00, inplace=True)
df_merged['Liquidado'].fillna(0.00, inplace=True)
df_merged['Arrecadado'] = df_merged['Arrecadado'] * bid_rate
df_merged['Liquidado'] = df_merged['Liquidado'] * bid_rate
df_merged["dt_insert"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
df_merged['dt_insert'] = pd.to_datetime(df_merged['dt_insert'])

/tmp/ipykernel_91484/774536462.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_merged['Arrecadado'].fillna(0.00, inplace=True)
/tmp/ipykernel_91484/774536462.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_merged['Liquidado'].fillna(0.00, inplace=True)

In [27]:
df_merged

,ID Fonte Recurso,Nome Fonte Recurso,Receita,Arrecadado,Despesa,Liquidado,dt_insert
0,001,TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11130111 - IRRF - IMP.RENDA PESSOA FISICA-PRIN...,22169390125.47,31900119 - ATRASADOS-OUTROS PODERES/MINIST.PUB...,414315941.51,2024-07-01 21:17:27
1,001,TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11130111 - IRRF - IMP.RENDA PESSOA FISICA-PRIN...,22169390125.47,31900124 - COMPLEMENTACAO DE APOSENTADORIA,9614159157.09,2024-07-01 21:17:27
2,001,TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11130111 - IRRF - IMP.RENDA PESSOA FISICA-PRIN...,22169390125.47,31900125 - COMPLEMENTACAO DE APOSENTADORIA - 1...,646903305.81,2024-07-01 21:17:27
3,001,TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11130111 - IRRF - IMP.RENDA PESSOA FISICA-PRIN...,22169390125.47,31900325 - COMPLEMENTACAO DE PENSAO,56870928.77,2024-07-01 21:17:27
4,001,TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,11130111 - IRRF - IMP.RENDA PESSOA FISICA-PRIN...,22169390125.47,31900326 - COMPLEMENTACAO DE PENSAO - 13º SALARIO,2709618.98,2024-07-01 21:17:27
...,...,...,...,...,...,...,...
63338,087,OP.CRED.CONTR.EXTERIOR-DOT.INIC.CR.SUP-INTRA,89100011 - INTEGRALIZACAO CAPITAL SOCIAL-PRINC...,241240537.09,44905112 - INSTALACOES,13220507.61,2024-07-01 21:17:27
63339,087,OP.CRED.CONTR.EXTERIOR-DOT.INIC.CR.SUP-INTRA,89100011 - INTEGRALIZACAO CAPITAL SOCIAL-PRINC...,241240537.09,44905130 - EXECUCAO DE OBRAS E INSTALACOES,170535224.05,2024-07-01 21:17:27
63340,087,OP.CRED.CONTR.EXTERIOR-DOT.INIC.CR.SUP-INTRA,89100011 - INTEGRALIZACAO CAPITAL SOCIAL-PRINC...,241240537.09,44905210 - VEICULOS DIVERSOS,3922934.50,2024-07-01 21:17:27
63341,087,OP.CRED.CONTR.EXTERIOR-DOT.INIC.CR.SUP-INTRA,89100011 - INTEGRALIZACAO CAPITAL SOCIAL-PRINC...,241240537.09,44905234 - OUTROS EQUIPAMENTOS E MATERIAL PERM...,10900658.25,2024-07-01 21:17:27
63342,099,EXTRA ORCAMENTARIA,13210011 - REMUNERACAO DEPOSITOS BANCARIOS - ...,0.00,NaN,0.00,2024-07-01 21:17:27

In [ ]:
df_merged['Margem Bruta'] = df_merged['Arrecadado'] - df_merged['Liquidado']
df_margem_bruta = df_merged.groupby(['ID Fonte Recurso', 'Nome Fonte Recurso'])['Margem Bruta'].sum().reset_index()
df_margem_bruta = df_margem_bruta.sort_values(by='Margem Bruta', ascending=False)
top_5_fontes = df_margem_bruta.head(5)
print("As 5 fontes de recursos com melhor margem bruta são:")
print(top_5_fontes[['ID Fonte Recurso', 'Nome Fonte Recurso', 'Margem Bruta']])

As 5 fontes de recursos com melhor margem bruta são:
  ID Fonte Recurso                            Nome Fonte Recurso  Margem Bruta
2              003  RECURSOS VINCULADOS-FUNDO ESPECIAL DE DESPES 5607091048.62
6              007  OP.CRED.E CONTRIB.DO EXTERIOR-DOT.INIC.CR.SU 4513392886.48
1              002                 RECURSOS VINCULADOS ESTADUAIS 3667885820.76
3              004        REC.PROPRIO-ADM.IND.-DOT.INIC.CR.SUPL. 3537201562.60
4              005                  RECURSOS VINCULADOS FEDERAIS 2568505194.67

In [15]:
df_merged

,ID Fonte Recurso,Nome Fonte Recurso,Arrecadado,Liquidado,dt_insert
0,001,TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR,755069075741.17,761629054293.34,2024-07-01 14:47:11
1,002,RECURSOS VINCULADOS ESTADUAIS,269273764451.93,265605878631.17,2024-07-01 14:47:11
2,003,RECURSOS VINCULADOS-FUNDO ESPECIAL DE DESPES,28276722671.90,22669631623.28,2024-07-01 14:47:11
3,004,REC.PROPRIO-ADM.IND.-DOT.INIC.CR.SUPL.,56511589734.29,52974388171.68,2024-07-01 14:47:11
4,005,RECURSOS VINCULADOS FEDERAIS,44597592235.13,42029087040.45,2024-07-01 14:47:11
5,006,OUTRAS FONTES DE RECURSOS,5670791635.18,3197029036.03,2024-07-01 14:47:11
6,007,OP.CRED.E CONTRIB.DO EXTERIOR-DOT.INIC.CR.SU,12376224513.05,7862831626.57,2024-07-01 14:47:11
7,041,TESOURO - CREDITO POR SUPERAVIT FINANCEIRO,0.05,7362312397.54,2024-07-01 14:47:11
8,042,REC.VINC.ESTADUAIS-CRED.SUPERAVIT FINANCEIRO,27811.77,2723974339.75,2024-07-01 14:47:11
9,043,F.E.D - CREDITO POR SUPERAVIT FINANCEIRO,0.00,161756266.18,2024-07-01 14:47:11
10,044,REC.PROP.ADM.IND-CRED.P/SUPERVAVIT FINANCEIR,2991329.70,2452167769.02,2024-07-01 14:47:11
11,045,REC.VINC.TRANSF.FEDERAL/SUPERAVIT FINANC.,678.56,1694331667.54,2024-07-01 14:47:11
12,047,REC.OPERAC. DE CREDITO-P/SUPERAVIT FINANCEIR,247368672.37,4638492444.04,2024-07-01 14:47:11
13,081,TESOURO-DOT.INICIAL E CRED.SUPLEMENTAR-INTRA,160756796425.24,160672067571.71,2024-07-01 14:47:11
14,082,RECURSOS VINCULADOS ESTADUAIS-INTRA,2109851558.52,2109851558.52,2024-07-01 14:47:11
15,083,RECURSOS VINCULADOS-FUNDO ESP. DESPESA-INTRA,248000956.52,244121178.23,2024-07-01 14:47:11
16,084,REC.PROPRIO-ADM.IND.-DOT.INIC.CR.SUPL.-INTRA,22732664.95,14250558.31,2024-07-01 14:47:11
17,085,RECURSOS VINCULADOS FEDERAIS-INTRA,1172941168.20,1172941168.20,2024-07-01 14:47:11
18,086,OUTRAS FONTES DE RECURSOS-INTRA,713605495.45,713605495.45,2024-07-01 14:47:11
19,087,OP.CRED.CONTR.EXTERIOR-DOT.INIC.CR.SUP-INTRA,241240537.09,241240537.09,2024-07-01 14:47:11
20,099,EXTRA ORCAMENTARIA,0.00,0.00,2024-07-01 14:47:11

Inserção dos dados

In [17]:
from google.cloud import bigquery
from google.oauth2 import service_account

credentials = service_account.Credentials.from_service_account_file(
    '/mnt/c/airflow/credentials/regal-state-348418-21234a5379b6.json',
    scopes=["https://www.googleapis.com/auth/cloud-platform"],
)

client = bigquery.Client(project='regal-state-348418', credentials=credentials)

job_config = bigquery.LoadJobConfig(write_disposition='WRITE_TRUNCATE')

table_id = 'regal-state-348418.dataset_karhub.fonte_recursos'

try:
    job = client.load_table_from_dataframe(
        df_merged, table_id, job_config=job_config
    )

    job.result()

    print(f"Dados carregados com sucesso na tabela {table_id}.")

except Exception as e:
    print(f"Erro ao carregar dados para o BigQuery: {e}")

Erro ao carregar dados para o BigQuery: 403 POST https://bigquery.googleapis.com/upload/bigquery/v2/projects/regal-state-348418/jobs?uploadType=multipart: Access Denied: Project regal-state-348418: User does not have bigquery.jobs.create permission in project regal-state-348418.

Validando a conversão dos dados csv para o formato feather

In [ ]:
import pandas as pd
import time
import os

data = {
    'col1': range(1000000),
    'col2': range(1000000)
}
df = pd.DataFrame(data)

start_time = time.time()
df.to_csv('example.csv', index=False)
csv_write_time = time.time() - start_time

start_time = time.time()
df.to_feather('example.feather')
feather_write_time = time.time() - start_time

start_time = time.time()
df_csv = pd.read_csv('example.csv')
csv_read_time = time.time() - start_time

start_time = time.time()
df_feather = pd.read_feather('example.feather')
feather_read_time = time.time() - start_time

csv_size = os.path.getsize('example.csv')
feather_size = os.path.getsize('example.feather')

print(f"Tempo de escrita CSV: {csv_write_time:.2f} segundos")
print(f"Tempo de escrita Feather: {feather_write_time:.2f} segundos")
print(f"Tempo de leitura CSV: {csv_read_time:.2f} segundos")
print(f"Tempo de leitura Feather: {feather_read_time:.2f} segundos")
print(f"Tamanho do arquivo CSV: {csv_size / 1024:.2f} KB")
print(f"Tamanho do arquivo Feather: {feather_size / 1024:.2f} KB")

Tempo de escrita CSV: 0.71 segundos
Tempo de escrita Feather: 0.06 segundos
Tempo de leitura CSV: 0.13 segundos
Tempo de leitura Feather: 0.04 segundos
Tamanho do arquivo CSV: 13454.87 KB
Tamanho do arquivo Feather: 7823.27 KB